import type {
  AccessCertificateId,
  IntendedUseId,
  LocalisedText,
  OrganisationId,
  RegistrationCertificateId,
  RelyingPartyId,
  RelyingPartyInstanceId,
  RelyingPartyServiceId,
  TenantId,
} from "@edtp/shared";
import type { ClaimPath } from "../verification/claim-path.js";
import type { TrustEnvironment } from "./trust-environment.js";

/**
 * The shared kernel: tenancy, the registered Relying Party structure, and the
 * trust material bound to it.
 *
 * Aligned with ARF 3.0.0 §3.11 and TS5 v1.5 (20.08.2026). The TS5 class each object
 * corresponds to is named in its doc comment, because the platform model must remain
 * expressible in the Registrar's data model — a later real Registrar integration
 * should be a mapping exercise, not a redesign.
 */

/** Platform customer account: the administrative and isolation boundary. */
export interface Tenant {
  readonly id: TenantId;
  readonly name: string;
  readonly createdAt: Date;
}

/**
 * A legal entity managed within a tenant.
 *
 * TS5 `WalletRelyingParty` inherits from `Provider` and `LegalEntity`. The fields
 * kept here are the ones V0 needs: the name, at least one official identifier, and
 * the Member State of establishment.
 *
 * TS5 §2.4.3.1 states that an identifier of type
 * `http://data.europa.eu/eudi/id/EUID` (European unique identifier) SHALL be used by
 * default where available in the national business register, and otherwise the
 * Member State defines the national scheme. V0 records the scheme explicitly rather
 * than assuming one.
 */
export interface OfficialIdentifier {
  /** Identifier scheme URI, e.g. `http://data.europa.eu/eudi/id/EUID`. */
  readonly scheme: string;
  readonly value: string;
}

export interface Organisation {
  readonly id: OrganisationId;
  readonly tenantId: TenantId;
  readonly legalName: string;
  readonly officialIdentifiers: readonly OfficialIdentifier[];
  /** ISO 3166-1 alpha-2 code of the Member State of establishment. */
  readonly memberState: string;
  /** TS5 `WalletRelyingParty.isPSB` — whether the entity is a public sector body. */
  readonly isPublicSectorBody: boolean;
  readonly createdAt: Date;
}

/**
 * An Organisation's registration as a Relying Party.
 *
 * ARF §3.11.1: the Registrar assigns an EU-wide unique Relying Party identifier.
 * `AS-MS-27-043` (`Reg_32`) requires that identifier to appear in the access
 * certificate, and `EW-DM-44-011` (`RPRC_07`) in the registration certificate;
 * `EW-DM-44-013` (`RPRC_08`) requires it to be identical across all of an entity's
 * registration certificates. It is therefore assigned externally and is never
 * minted by the platform.
 */
export interface RelyingParty {
  readonly id: RelyingPartyId;
  readonly tenantId: TenantId;
  readonly organisationId: OrganisationId;
  /** Registrar-assigned, EU-wide unique. Never generated by the platform. */
  readonly registrarAssignedIdentifier: string;
  /** Identifier of the Registrar that assigned it, for provenance. */
  readonly registrar: string;
  /** TS5 `WalletRelyingParty.registryURI`, provided by the Registrar on registration. */
  readonly registryUri?: string;
  /** TS5 `WalletRelyingParty.tradeName` [0..1]. */
  readonly tradeName?: string;
  readonly trustEnvironment: TrustEnvironment;
  readonly createdAt: Date;
}

/**
 * TS5 `WalletRelyingPartyService`. ARF §3.11.2: the Service identifier "can be
 * freely chosen by the Relying Party, as long as it is unique for the given Relying
 * Party", and `AS-MS-27-045` (`Reg_33`) requires it in the access certificate.
 *
 * TS5 makes `serviceIdentifier` `[0..1]`. The platform requires it unconditionally,
 * because its model is multi-service from the start and its engine tenant mapping is
 * per Service (ADR 0002 Decision 3). That is a deliberate stricter-than-TS5 choice,
 * not a conformance claim — see ADR 0005 Decision 1d.
 */
export interface RelyingPartyService {
  readonly id: RelyingPartyServiceId;
  readonly tenantId: TenantId;
  readonly relyingPartyId: RelyingPartyId;
  /** RP-chosen, unique within the Relying Party. */
  readonly serviceIdentifier: string;
  /** TS5 `serviceTradeName` [1..1]. Displayed to the User per `AS-WP-06-007` (`RPA_06`). */
  readonly serviceTradeName: string;
  /** TS5 `srvDescription` [1..*]. */
  readonly description: readonly LocalisedText[];
  /**
   * HTTPS allow-list for result callbacks. An arbitrary per-request URL is refused
   * (SSRF protection) — a request may only name a URL registered here.
   */
  readonly callbackUrlAllowList: readonly string[];
  readonly createdAt: Date;
}

/**
 * One credential the intended use may request, with the attributes registered for it.
 *
 * TS5 `Credential`: `format` [1..1], `meta` [1..1] (`vct_values` for SD-JWT VC,
 * `doctype` for mdoc), `claims` [1..*]. `IntendedUse.credentials` is `[1..*]`, so an
 * intended use may register several credentials even though a V0 policy requests one.
 */
export const CREDENTIAL_FORMATS = ["dc+sd-jwt", "mso_mdoc"] as const;
export type CredentialFormat = (typeof CREDENTIAL_FORMATS)[number];

export interface RegisteredCredential {
  readonly format: CredentialFormat;
  /** SD-JWT VC type values. Present when `format` is `dc+sd-jwt`. */
  readonly vctValues?: readonly string[];
  /** mdoc document type. Present when `format` is `mso_mdoc`. */
  readonly doctype?: string;
  /** The attributes registered as requestable, as OpenID4VP claim paths. */
  readonly claims: readonly ClaimPath[];
}

/**
 * TS5 `IntendedUse`.
 *
 * `AS-MS-27-016` (`Reg_10d`): a Relying Party registers which of its intended uses
 * apply to each registered Service. `EW-DM-44-014` (`RPRC_09`): a separate
 * registration certificate is created for each combination of intended use and
 * Service. `intendedUseIdentifier` is Registrar-provided, never platform-minted.
 *
 * `purpose` and `privacyPolicy` are `[1..*]` localised, and the Wallet displays both
 * when asking for User approval — `AS-WP-06-015` (`RPA_10`).
 */
export interface IntendedUse {
  readonly id: IntendedUseId;
  readonly tenantId: TenantId;
  readonly relyingPartyServiceId: RelyingPartyServiceId;
  /** Registrar-provided unique identifier of the registered intended use. */
  readonly intendedUseIdentifier: string;
  readonly purpose: readonly LocalisedText[];
  readonly privacyPolicyUris: readonly LocalisedText[];
  /** Registered attributes per credential. TS5 `IntendedUse.credentials` [1..*]. */
  readonly registeredCredentials: readonly RegisteredCredential[];
  /** TS5 `createdAt` — validity start of the intended use. */
  readonly validFrom: Date;
  /** TS5 `revokedAt` [0..1] — expiry or revocation of the intended use. */
  readonly revokedAt?: Date;
  readonly createdAt: Date;
}

/**
 * Reference to the JWT registration certificate for exactly one intended use of one
 * Service — `EW-DM-44-014` (`RPRC_09`).
 *
 * ARF §3.19: a registration certificate is a JWT per RFC 7519, not an X.509
 * certificate. `EW-DM-44-023` (`RPRC_19`) requires a Relying Party Instance to
 * include a single applicable registration certificate in each presentation request,
 * **by value**.
 *
 * V0 has no reachable provider of registration certificates (blocker B3), so this
 * record may exist without a JWT. When `jwt` is absent the compiler produces a plan
 * with no registration certificate and that fact is reported, never simulated.
 */
export interface RegistrationCertificate {
  readonly id: RegistrationCertificateId;
  readonly tenantId: TenantId;
  readonly relyingPartyServiceId: RelyingPartyServiceId;
  readonly intendedUseId: IntendedUseId;
  /** The certificate as a compact JWS, when one has been obtained. */
  readonly jwt?: string;
  /** Provider that issued it, for provenance. */
  readonly provider?: string;
  readonly notBefore?: Date;
  readonly notAfter?: Date;
  readonly trustEnvironment: TrustEnvironment;
  readonly createdAt: Date;
}

/**
 * The X.509 access certificate bound to the Relying Party identifier, the Service
 * identifier and a key held by the Relying Party Instance.
 *
 * ARF §3.18: an access certificate is an RFC 5280 certificate complying with
 * ETSI TS 119 411-8. `AS-WP-06-004` (`RPA_03`) requires Relying Party authentication
 * in every presentation transaction using one, and `AS-WP-06-005` (`RPA_04`) requires
 * the Wallet to accept only trust anchors from the notified Access CA LoTEs.
 *
 * **Private keys never leave the key store.** The platform records only a reference
 * to the engine key chain holding the key; no private key material is modelled here,
 * so none can be persisted or logged by construction.
 */
export interface AccessCertificate {
  readonly id: AccessCertificateId;
  readonly tenantId: TenantId;
  readonly relyingPartyId: RelyingPartyId;
  readonly relyingPartyServiceId: RelyingPartyServiceId;
  /** Opaque reference to the key chain in the engine key store. Never a key. */
  readonly keyBindingRef: string;
  /** Subject common name, for operator display only. */
  readonly subject?: string;
  /** Issuing Access CA, for provenance and for trust-anchor review. */
  readonly issuer?: string;
  readonly notBefore?: Date;
  readonly notAfter?: Date;
  readonly trustEnvironment: TrustEnvironment;
  readonly createdAt: Date;
}

/**
 * The platform-hosted instance serving a Relying Party Service.
 *
 * ARF §3.11.3: a Relying Party Instance is "a system consisting of software and
 * hardware to interact with Wallet Units", and may hold multiple access certificates
 * if it serves multiple Services.
 *
 * Maps 1:1 to an engine tenant (ADR 0002 Decision 3), because the engine scopes key
 * material, certificates and registrar configuration per tenant while ARF scopes
 * those to a Service. `engineTenantRef` is infrastructure metadata and is never
 * exposed in the business API.
 */
export interface RelyingPartyInstance {
  readonly id: RelyingPartyInstanceId;
  readonly tenantId: TenantId;
  readonly relyingPartyServiceId: RelyingPartyServiceId;
  readonly engineTenantRef: string;
  readonly trustEnvironment: TrustEnvironment;
  readonly createdAt: Date;
}

/**
 * Placeholder for Milestone 2. Types only in Milestone 1, per the V0 plan, so the
 * shared kernel is shaped for issuance without implementing it.
 *
 * `AS-AP-44-004` (`RPRC_22`) requires an Attestation Provider to include its
 * registration certificate in its Credential Issuer metadata by value, and
 * `AS-AP-44-005` (`RPRC_22a`) / `AS-AP-44-007` (`RPRC_23`) make the Wallet refuse to
 * request issuance when that certificate is absent, invalid or does not cover the
 * attestation type. That is stricter than the presentation path and is recorded as
 * blocker B4.
 */
export interface AttestationProvider {
  readonly id: string;
  readonly tenantId: TenantId;
  readonly organisationId: OrganisationId;
  readonly registrarAssignedIdentifier: string;
  readonly trustEnvironment: TrustEnvironment;
  readonly createdAt: Date;
}
